name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.9"
          channel: 'stable'
          cache: true
      # 12
      - name: Get dependencies
        run: flutter pub get; flutter pub run build_runner build --delete-conflicting-outputs   


        
      # Runs a set of commands using the runners shell
      - name: Start release build
        run: fvm flutter build apk --release --target-platform android-arm,android-arm64
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
         name: apk
         path: build\app\outputs\flutter-apk\app-release.apk
 
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
         name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ github.run_number }}
         release_name: ${{ github.event.repository.name }} v${{ github.run_number }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: apk/app-debug.apk
         asset_name: ${{ github.event.repository.name }}.apk
         asset_content_type: application/zip
